name: "Get K8S Namespace"
description: "Determines and sanitizes the K8S namespace based on the branch name"
outputs:
  namespace:
    description: "The sanitized namespace name"
    value: ${{ steps.calc.outputs.namespace }}

runs:
  using: "composite"
  steps:
    - id: calc
      shell: bash
      run: |
        # 1. Identify the event type
        EVENT_NAME="${{ github.event_name }}"

        # 2. Assign the reference based on event type
        if [[ "$EVENT_NAME" == "delete" ]]; then
          # For delete, 'ref_name' is usually the default branch (main).
          # 'event.ref' contains the actual deleted branch name.
          REF_NAME="${{ github.event.ref }}"
        else
          REF_NAME="${{ github.ref_name }}"
        fi

        # 3. Strip 'refs/heads/' prefix if it exists
        STRIPPED=$(echo "$REF_NAME" | sed 's|refs/heads/||')

        # 4. Logic for 'main' (Production)
        if [[ "$STRIPPED" == "main" ]]; then
          # ONLY return project if we aren't in a delete event
          if [[ "$EVENT_NAME" == "delete" ]]; then
             echo "Error: Attempted to delete 'main' branch context."
             exit 1
          fi
          echo "namespace=project" >> $GITHUB_OUTPUT
        else
          # 5. Sanitize feature branches
          CLEAN=$(echo "$STRIPPED" | sed 's/\//-/g' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]//g')

          if [[ -z "$CLEAN" || "$CLEAN" == "project" ]]; then
            echo "Error: Sanitization resulted in an invalid or protected namespace."
            exit 1
          fi

          echo "namespace=$CLEAN" >> $GITHUB_OUTPUT
        fi
